import type { Project } from "@/types";

const now = Date.now();
const day = 86400000;

export const MOCK_PROJECTS: Project[] = [
  {
    id: "1", mintAddress: "9xQeWvG816bUx9EPjHmaT23yvVM2ZWbrrpZb9PusVFin",
    name: "HumbleAI", symbol: "HAI", description: "Decentralized AI compute marketplace built on Solana with verifiable inference proofs.",
    logoUrl: undefined, creatorWallet: "7WQiW...wZJ",
    totalSupply: "1000000000", decimals: 9,
    trustScore: 94, liquidityLocked: true, lockDurationSeconds: 365 * 86400,
    lockUnlockAt: new Date(now + 365 * day).toISOString(),
    vestingEnabled: true, creatorAllocationPct: 5, mintRevoked: true, freezeRevoked: true,
    dex: "raydium", status: "live", totalInvestedSol: 4250, holderCount: 1823,
    createdAt: new Date(now - 120 * day).toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "2", mintAddress: "DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263",
    name: "SolVault", symbol: "SVLT", description: "Automated yield optimizer with on-chain risk scoring and dynamic rebalancing.",
    logoUrl: undefined, creatorWallet: "3HpC...mX9",
    totalSupply: "500000000", decimals: 9,
    trustScore: 82, liquidityLocked: true, lockDurationSeconds: 180 * 86400,
    lockUnlockAt: new Date(now + 90 * day).toISOString(),
    vestingEnabled: true, creatorAllocationPct: 8, mintRevoked: true, freezeRevoked: false,
    dex: "orca", status: "live", totalInvestedSol: 1890, holderCount: 742,
    createdAt: new Date(now - 45 * day).toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "3", mintAddress: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
    name: "RustDEX", symbol: "RDEX", description: "Fully on-chain order book DEX with zero off-chain components. No servers. No trust.",
    logoUrl: undefined, creatorWallet: "Bk7mF...9Lp",
    totalSupply: "2000000000", decimals: 6,
    trustScore: 91, liquidityLocked: true, lockDurationSeconds: 365 * 86400,
    lockUnlockAt: new Date(now + 280 * day).toISOString(),
    vestingEnabled: true, creatorAllocationPct: 3, mintRevoked: true, freezeRevoked: true,
    dex: "raydium", status: "live", totalInvestedSol: 7800, holderCount: 3104,
    createdAt: new Date(now - 200 * day).toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "4", mintAddress: "So11111111111111111111111111111111111111112",
    name: "AnchorDAO", symbol: "ADAO", description: "On-chain governance for Solana protocols. Proposals, votes, execution — all verifiable.",
    logoUrl: undefined, creatorWallet: "9mP4...3Qn",
    totalSupply: "100000000", decimals: 9,
    trustScore: 73, liquidityLocked: true, lockDurationSeconds: 90 * 86400,
    lockUnlockAt: new Date(now + 30 * day).toISOString(),
    vestingEnabled: false, creatorAllocationPct: 10, mintRevoked: false, freezeRevoked: true,
    dex: "orca", status: "live", totalInvestedSol: 560, holderCount: 289,
    createdAt: new Date(now - 12 * day).toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "5", mintAddress: "mSoLzYCxHdYgdzU16g5QSh3i5K3z3KZK7ytfqcJm7So",
    name: "ZenProtocol", symbol: "ZEN", description: "Privacy-preserving DeFi using ZK proofs. All balances are private by default.",
    logoUrl: undefined, creatorWallet: "FpQm...7Xt",
    totalSupply: "750000000", decimals: 9,
    trustScore: 58, liquidityLocked: true, lockDurationSeconds: 30 * 86400,
    lockUnlockAt: new Date(now + 8 * day).toISOString(),
    vestingEnabled: true, creatorAllocationPct: 7, mintRevoked: false, freezeRevoked: false,
    dex: "raydium", status: "live", totalInvestedSol: 340, holderCount: 178,
    createdAt: new Date(now - 5 * day).toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "6", mintAddress: "Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB",
    name: "ChainLink SOL", symbol: "CLINK", description: "Oracle network for Solana. Real-world data feeds with cryptographic proofs.",
    logoUrl: undefined, creatorWallet: "2Wx8...Np4",
    totalSupply: "300000000", decimals: 9,
    trustScore: 87, liquidityLocked: true, lockDurationSeconds: 365 * 86400,
    lockUnlockAt: new Date(now + 200 * day).toISOString(),
    vestingEnabled: true, creatorAllocationPct: 6, mintRevoked: true, freezeRevoked: true,
    dex: "orca", status: "live", totalInvestedSol: 2100, holderCount: 934,
    createdAt: new Date(now - 60 * day).toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "7", mintAddress: "4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R",
    name: "FluxBridge", symbol: "FLUX", description: "Cross-chain bridge with multi-sig validation. Assets move only when consensus is reached.",
    logoUrl: undefined, creatorWallet: "Hq3K...8Vn",
    totalSupply: "1500000000", decimals: 9,
    trustScore: 35, liquidityLocked: true, lockDurationSeconds: 14 * 86400,
    lockUnlockAt: new Date(now + 2 * day).toISOString(),
    vestingEnabled: false, creatorAllocationPct: 10, mintRevoked: false, freezeRevoked: false,
    dex: "raydium", status: "live", totalInvestedSol: 89, holderCount: 67,
    createdAt: new Date(now - 3 * day).toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "8", mintAddress: "7vfCXTUXx5WJV5JADk17DUJ4ksgau7utNKj4b963voxs",
    name: "NovaNFT", symbol: "NOVA", description: "NFT fractionalization platform. Own a piece of blue-chip NFTs with on-chain collateral.",
    logoUrl: undefined, creatorWallet: "5Rj9...2Lw",
    totalSupply: "250000000", decimals: 9,
    trustScore: 76, liquidityLocked: true, lockDurationSeconds: 180 * 86400,
    lockUnlockAt: new Date(now + 110 * day).toISOString(),
    vestingEnabled: true, creatorAllocationPct: 9, mintRevoked: true, freezeRevoked: false,
    dex: "orca", status: "live", totalInvestedSol: 920, holderCount: 412,
    createdAt: new Date(now - 30 * day).toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "9", mintAddress: "AGFEad2et2ZJif9jaGpdMixQqvW5i81aBghCMykR5fg",
    name: "PulseStake", symbol: "PLS", description: "Liquid staking for Solana validators. Stake, earn, and use as collateral simultaneously.",
    logoUrl: undefined, creatorWallet: "6Ym7...4Qs",
    totalSupply: "800000000", decimals: 9,
    trustScore: 96, liquidityLocked: true, lockDurationSeconds: 365 * 86400 * 2,
    lockUnlockAt: new Date(now + 600 * day).toISOString(),
    vestingEnabled: true, creatorAllocationPct: 4, mintRevoked: true, freezeRevoked: true,
    dex: "raydium", status: "live", totalInvestedSol: 12400, holderCount: 5891,
    createdAt: new Date(now - 365 * day).toISOString(), updatedAt: new Date().toISOString(),
  },
  {
    id: "10", mintAddress: "kinXdEcpDQeHPEuQnqmUgtYykqKTVdfKksHuup3v6rm",
    name: "MetaScore", symbol: "META", description: "Reputation scoring for on-chain identities. Build verifiable credit history from your wallet activity.",
    logoUrl: undefined, creatorWallet: "8Tx2...9Km",
    totalSupply: "400000000", decimals: 9,
    trustScore: 69, liquidityLocked: true, lockDurationSeconds: 90 * 86400,
    lockUnlockAt: new Date(now + 45 * day).toISOString(),
    vestingEnabled: true, creatorAllocationPct: 8, mintRevoked: false, freezeRevoked: true,
    dex: "orca", status: "live", totalInvestedSol: 445, holderCount: 234,
    createdAt: new Date(now - 20 * day).toISOString(), updatedAt: new Date().toISOString(),
  },
];
