import type {
  ChartPoint,
  Investment,
  PlatformStats,
  PortfolioPosition,
  Project,
  TrustScoreHistory,
} from "@/types";
import { calculateTrustScore } from "@/lib/trust-score";

const programId = "FGQ16c5cmDkmDRG27kt27VrZP3FnhHTH3qtrXoMg3PGr";
const now = Date.now();
const day = 86400000;

function iso(offsetDays: number) {
  return new Date(now + offsetDays * day).toISOString();
}

function activity(seed: number): ChartPoint[] {
  return ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"].map((label, index) => ({
    label,
    value: Math.round(28 + Math.sin(seed + index) * 14 + index * seed * 1.8),
  }));
}

function tx(index: number) {
  return `${index}vX9FeHumble${index}Trust9QpM7sR4K2ePDA${index}Lk8sV${index}xR`;
}

function investment(projectId: string, index: number, amountSol: number): Investment {
  return {
    id: `inv-${projectId}-${index}`,
    projectId,
    walletAddress: `7hT${index}KJ4nQxP2Vh9uR6zY${index}SolVaultInvestor${index}`,
    amountSol,
    tokenAmount: `${Math.round(amountSol * 94000)}`,
    txSignature: tx(index),
    createdAt: iso(-index * 2),
  };
}

type ProjectSeed = Omit<
  Project,
  "trustScore" | "investments" | "scoreHistory" | "updatedAt" | "sevenDayActivity"
> & {
  activitySeed: number;
};

function project(seed: ProjectSeed): Project {
  const trust = calculateTrustScore(seed);
  const history: TrustScoreHistory[] = [
    {
      id: `${seed.id}-score-1`,
      projectId: seed.id,
      score: Math.max(12, trust.score - 18),
      breakdown: trust.breakdown,
      reason: "Initial launch configuration recorded.",
      createdAt: seed.createdAt,
    },
    {
      id: `${seed.id}-score-2`,
      projectId: seed.id,
      score: trust.score,
      breakdown: trust.breakdown,
      reason: "Authorities and vault state verified on-chain.",
      createdAt: iso(-2),
    },
  ];

  return {
    ...seed,
    updatedAt: iso(-1),
    trustScore: trust.score,
    sevenDayActivity: activity(seed.activitySeed),
    investments: [
      investment(seed.id, seed.activitySeed, Math.round(seed.totalInvestedSol * 0.08)),
      investment(seed.id, seed.activitySeed + 1, Math.round(seed.totalInvestedSol * 0.05)),
      investment(seed.id, seed.activitySeed + 2, Math.round(seed.totalInvestedSol * 0.03)),
    ],
    scoreHistory: history,
  };
}

export const projects: Project[] = [
  project({
    id: "aurora-vault",
    mintAddress: "AURoVaU1t2rwT43nFh7X5yM2sPDA9dHumble111",
    name: "Aurora Vault",
    symbol: "AURV",
    description: "A DeFi coordination token with locked protocol liquidity and staged builder unlocks.",
    creatorWallet: "8xM6oQwWqFdKp9q4n7N3tHzxAx1veCMn2VDLzk9rXwQ",
    totalSupply: "1000000000",
    decimals: 9,
    liquidityLocked: true,
    lockDurationSeconds: 365 * 86400,
    lockUnlockAt: iso(342),
    vestingEnabled: true,
    creatorAllocationPct: 4.5,
    mintRevoked: true,
    freezeRevoked: true,
    dex: "raydium",
    vaultPda: "6vauLtAuroraPDA9q3NtX4cY2pHumbleTrust",
    programId,
    status: "live",
    totalInvestedSol: 8420,
    holderCount: 12848,
    createdAt: iso(-96),
    volume24h: 1280,
    price: 0.0142,
    change24h: 8.4,
    goalSol: 10000,
    marketCap: 14200000,
    circulatingSupply: "420000000",
    activitySeed: 2,
  }),
  project({
    id: "kernel-market",
    mintAddress: "KrnLMrkt9Xw4pSolanaVaultTrustPDA222",
    name: "Kernel Market",
    symbol: "KERN",
    description: "Permissionless tooling for protocol-owned marketplaces with programmatic fee routing.",
    creatorWallet: "Ds6qFh3xW4n8A9bR4hQ2mZp7kE1nN7xM0uL5sQv",
    totalSupply: "500000000",
    decimals: 9,
    liquidityLocked: true,
    lockDurationSeconds: 180 * 86400,
    lockUnlockAt: iso(164),
    vestingEnabled: true,
    creatorAllocationPct: 7.2,
    mintRevoked: true,
    freezeRevoked: true,
    dex: "orca",
    vaultPda: "KernVaultPDA3HumbleTrustLiquidityLock",
    programId,
    status: "locked",
    totalInvestedSol: 5320,
    holderCount: 6028,
    createdAt: iso(-43),
    volume24h: 780,
    price: 0.0088,
    change24h: 3.1,
    goalSol: 7000,
    marketCap: 4400000,
    circulatingSupply: "210000000",
    activitySeed: 4,
  }),
  project({
    id: "cipher-rail",
    mintAddress: "CiphrRail4JmSolanaPDAHumbleTrust333",
    name: "Cipher Rail",
    symbol: "RAIL",
    description: "Privacy-preserving payment rails with public launch accountability.",
    creatorWallet: "3B9k6nDqQfAj7hS2uR8cW5mV1tYzLk4pExG7aN",
    totalSupply: "750000000",
    decimals: 9,
    liquidityLocked: true,
    lockDurationSeconds: 90 * 86400,
    lockUnlockAt: iso(76),
    vestingEnabled: true,
    creatorAllocationPct: 9.8,
    mintRevoked: true,
    freezeRevoked: false,
    dex: "raydium",
    vaultPda: "RailVaultPDA9TrustCannotBeFaked",
    programId,
    status: "live",
    totalInvestedSol: 2140,
    holderCount: 2492,
    createdAt: iso(-14),
    volume24h: 332,
    price: 0.0031,
    change24h: -2.4,
    goalSol: 4200,
    marketCap: 2325000,
    circulatingSupply: "310000000",
    activitySeed: 6,
  }),
  project({
    id: "monolith-dao",
    mintAddress: "MonoDaoVaultHumbleTrustPDA444Solana",
    name: "Monolith DAO",
    symbol: "MONO",
    description: "Governance primitive with multisig-managed protocol parameters and immutable launch rules.",
    creatorWallet: "9Yp4Rc8nD2jVz7Qm1bL5xE6tHwK3sF0aUrN",
    totalSupply: "100000000",
    decimals: 6,
    liquidityLocked: true,
    lockDurationSeconds: 365 * 86400,
    lockUnlockAt: iso(358),
    vestingEnabled: true,
    creatorAllocationPct: 3.8,
    mintRevoked: true,
    freezeRevoked: true,
    dex: "orca",
    vaultPda: "MonoPDAHumbleTrustVaultLock365",
    programId,
    status: "live",
    totalInvestedSol: 11980,
    holderCount: 17620,
    createdAt: iso(-126),
    volume24h: 2014,
    price: 0.084,
    change24h: 12.7,
    goalSol: 12000,
    marketCap: 8400000,
    circulatingSupply: "82000000",
    activitySeed: 8,
  }),
  project({
    id: "forgepass",
    mintAddress: "ForgePassNftUtilityPDAHumble555",
    name: "ForgePass",
    symbol: "FORGE",
    description: "NFT access and token utility launch with fee sharing wired into the protocol vault.",
    creatorWallet: "7Qk2TxV6mZf4cNp9aD3Lh8sB1rYwJ5e",
    totalSupply: "250000000",
    decimals: 9,
    liquidityLocked: true,
    lockDurationSeconds: 30 * 86400,
    lockUnlockAt: iso(22),
    vestingEnabled: false,
    creatorAllocationPct: 8.5,
    mintRevoked: true,
    freezeRevoked: true,
    dex: "raydium",
    vaultPda: "ForgeVaultPDAThirtyDayLock",
    programId,
    status: "live",
    totalInvestedSol: 920,
    holderCount: 932,
    createdAt: iso(-5),
    volume24h: 88,
    price: 0.0019,
    change24h: 1.2,
    goalSol: 2000,
    marketCap: 475000,
    circulatingSupply: "82000000",
    activitySeed: 10,
  }),
  project({
    id: "open-orbit",
    mintAddress: "OpenOrbitPDAHumbleTrust666Sol",
    name: "Open Orbit",
    symbol: "ORBT",
    description: "Community launchpad token designed for public vesting and transparent treasury behavior.",
    creatorWallet: "2Yt9RjVm4Kb7qL6hP1xA8dN3sFz5Wc",
    totalSupply: "900000000",
    decimals: 9,
    liquidityLocked: true,
    lockDurationSeconds: 180 * 86400,
    lockUnlockAt: iso(148),
    vestingEnabled: true,
    creatorAllocationPct: 5,
    mintRevoked: true,
    freezeRevoked: true,
    dex: "raydium",
    vaultPda: "OrbitVaultPDA180DaysImmutable",
    programId,
    status: "locked",
    totalInvestedSol: 3870,
    holderCount: 4138,
    createdAt: iso(-34),
    volume24h: 544,
    price: 0.0064,
    change24h: 5.9,
    goalSol: 5000,
    marketCap: 5760000,
    circulatingSupply: "350000000",
    activitySeed: 12,
  }),
  project({
    id: "delta-mesh",
    mintAddress: "DeltaMeshLaunchPDAHumble777",
    name: "Delta Mesh",
    symbol: "MESH",
    description: "Infrastructure token with a shorter lock and partial authority revocation.",
    creatorWallet: "6Rm4zNwQ8cD1hX5pVk9sB2tL7yE3a",
    totalSupply: "300000000",
    decimals: 9,
    liquidityLocked: true,
    lockDurationSeconds: 30 * 86400,
    lockUnlockAt: iso(18),
    vestingEnabled: false,
    creatorAllocationPct: 10,
    mintRevoked: false,
    freezeRevoked: true,
    dex: "orca",
    vaultPda: "MeshVaultPDAShortLock",
    programId,
    status: "live",
    totalInvestedSol: 680,
    holderCount: 418,
    createdAt: iso(-3),
    volume24h: 36,
    price: 0.0014,
    change24h: -5.6,
    goalSol: 1800,
    marketCap: 420000,
    circulatingSupply: "120000000",
    activitySeed: 14,
  }),
  project({
    id: "northstar-ai",
    mintAddress: "NorthStarAIPDAHumble888",
    name: "Northstar AI",
    symbol: "NSTAR",
    description: "Agent network launch with hardcoded unlock windows and PDA-controlled fee routing.",
    creatorWallet: "5Cv8PnS2hK7mR4xT9dL1wV6yQ3aJz",
    totalSupply: "600000000",
    decimals: 9,
    liquidityLocked: true,
    lockDurationSeconds: 365 * 86400,
    lockUnlockAt: iso(333),
    vestingEnabled: true,
    creatorAllocationPct: 6,
    mintRevoked: true,
    freezeRevoked: true,
    dex: "raydium",
    vaultPda: "NStarVaultPDA365HumbleTrust",
    programId,
    status: "live",
    totalInvestedSol: 7210,
    holderCount: 9034,
    createdAt: iso(-68),
    volume24h: 1184,
    price: 0.011,
    change24h: 6.8,
    goalSol: 8000,
    marketCap: 6600000,
    circulatingSupply: "280000000",
    activitySeed: 16,
  }),
  project({
    id: "rift-pay",
    mintAddress: "RiftPayPDAHumble999",
    name: "Rift Pay",
    symbol: "RIFT",
    description: "Payments token waiting on a full lock verification before public exposure.",
    creatorWallet: "4Pa7hL9sD2kV8cQ1mN5rX3zWy6tU",
    totalSupply: "450000000",
    decimals: 6,
    liquidityLocked: false,
    lockDurationSeconds: 0,
    lockUnlockAt: iso(0),
    vestingEnabled: false,
    creatorAllocationPct: 12,
    mintRevoked: false,
    freezeRevoked: false,
    dex: "orca",
    vaultPda: "PendingVaultVerification",
    programId,
    status: "pending",
    totalInvestedSol: 140,
    holderCount: 52,
    createdAt: iso(-1),
    volume24h: 4,
    price: 0.0004,
    change24h: -14.3,
    goalSol: 1500,
    marketCap: 180000,
    circulatingSupply: "45000000",
    activitySeed: 18,
  }),
  project({
    id: "sentinel-labs",
    mintAddress: "SentinelLabsPDAHumbleTrust1010",
    name: "Sentinel Labs",
    symbol: "SENT",
    description: "Security research DAO token with a completed first lock window and clean creator history.",
    creatorWallet: "Au6mW3xJ8tN5rK1hQ9pL4sD2vY7c",
    totalSupply: "120000000",
    decimals: 9,
    liquidityLocked: true,
    lockDurationSeconds: 180 * 86400,
    lockUnlockAt: iso(-12),
    vestingEnabled: true,
    creatorAllocationPct: 4,
    mintRevoked: true,
    freezeRevoked: true,
    dex: "raydium",
    vaultPda: "SentinelVaultPDACompletedLock",
    programId,
    status: "completed",
    totalInvestedSol: 6310,
    holderCount: 7104,
    createdAt: iso(-188),
    volume24h: 476,
    price: 0.047,
    change24h: 2.7,
    goalSol: 6000,
    marketCap: 5640000,
    circulatingSupply: "94000000",
    activitySeed: 20,
  }),
];

export const platformStats: PlatformStats = {
  totalLockedSol: projects.reduce((sum, item) => sum + item.totalInvestedSol, 0),
  projectsLive: projects.filter((item) => item.status === "live" || item.status === "locked").length,
  rugsPrevented: 128,
  investorsProtected: projects.reduce((sum, item) => sum + item.holderCount, 0),
  volume24h: projects.reduce((sum, item) => sum + item.volume24h, 0),
};

export const portfolioPositions: PortfolioPosition[] = projects.slice(0, 4).map((item, index) => {
  const investedSol = [18.4, 11.2, 7.7, 24.9][index] ?? 5;
  const pnlPct = [22.8, 9.4, -4.1, 31.7][index] ?? 0;

  return {
    project: item,
    investedSol,
    currentValueSol: Number((investedSol * (1 + pnlPct / 100)).toFixed(2)),
    pnlPct,
  };
});

export function findProject(id: string) {
  return projects.find((projectItem) => projectItem.id === id);
}
